#!/bin/busybox sh

# Copyright (C) 2019 ealain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

/bin/busybox --install -s

echo "Hello from /init"

# Get the root= kernel parameter
mount -t proc proc /proc
read cmdline < /proc/cmdline
root_=${cmdline#*root=}
root=${root_% *}

# Switch root
mount -t devtmpfs none /dev
mkdir new_root
mount $root new_root
exec switch_root new_root /sbin/init

exec sh
